name: Docker Image CI

on:
  pull_request:
    branches: [ "build" ]
    types: ["closed"]
jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Set tag hash
      id: vars
      run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

    - name: Check tag hash
      run: echo ${{ steps.vars.outputs.sha_short }}

    - name: Build the Docker image
      run: docker build ./TutorManagementSystem --file ./TutorManagementSystem/API/Dockerfile -t ${{ vars.IMG_NAME }}:${{ steps.vars.outputs.sha_short }} -t ${{ vars.IMG_NAME }}:latest

    - name: Log in to github registry
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login ghcr.io -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Push version image
      run: docker push ${{ vars.IMG_NAME }}:${{ steps.vars.outputs.sha_short }}

    - name: Push latest image
      run: docker push ${{ vars.IMG_NAME }}:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: SSH to VPS and run docker container
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        passphrase: ${{ secrets.SSH_PASSPHASE }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.PORT }}
        script: |
          docker stop classntutor_be || true && docker rm classntutor_be || true  && docker rmi ${{ vars.IMG_NAME }}:latest || true
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login ghcr.io -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker pull ${{ vars.IMG_NAME }}:latest
          docker run -d --name classntutor_be --network proxy_manager_default --restart on-failure:5 -e ASPNETCORE_ENVIRONMENT="Staging" -e ASPNETCORE_URLS="http://+:80" -p 8080:80 ${{ vars.IMG_NAME }}:latest
